name: talk
dependencies:
- appnope=0.1.0=py35_0
- backports=1.0=py35_0
- bokeh=0.11.1=py35_0
- bottleneck=1.0.0=np110py35_0
- chest=0.2.3=py35_0
- cloudpickle=0.2.1=py35_1
- cycler=0.10.0=py35_0
- cython=0.24=py35_0
- dask=0.8.2=py35_0
- decorator=4.0.9=py35_0
- entrypoints=0.2=py35_1
- freetype=2.5.5=0
- get_terminal_size=1.0.0=py35_0
- hdf5=1.8.16=2
- heapdict=1.0.0=py35_0
- ipykernel=4.3.1=py35_0
- ipython=4.2.0=py35_0
- ipython_genutils=0.1.0=py35_0
- ipywidgets=4.1.1=py35_0
- jinja2=2.8=py35_0
- jsonschema=2.4.0=py35_0
- jupyter=1.0.0=py35_2
- jupyter_client=4.2.2=py35_0
- jupyter_console=4.1.1=py35_0
- jupyter_core=4.1.0=py35_0
- libpng=1.6.17=0
- llvmlite=0.10.0=py35_0
- locket=0.2.0=py35_0
- markupsafe=0.23=py35_0
- matplotlib=1.5.1=np110py35_0
- mistune=0.7.2=py35_1
- mkl=11.3.1=0
- nbconvert=4.2.0=py35_0
- nbformat=4.0.1=py35_0
- notebook=4.2.0=py35_0
- numba=0.25.0=np110py35_0
- numexpr=2.5.2=np110py35_0
- numpy=1.10.4=py35_0
- openssl=1.0.2g=0
- pandas=0.18.1=np110py35_0
- partd=0.3.2=py35_1
- path.py=8.2.1=py35_0
- pexpect=4.0.1=py35_0
- pickleshare=0.5=py35_0
- pip=8.1.1=py35_1
- psutil=4.1.0=py35_1
- ptyprocess=0.5=py35_0
- pygments=2.1.3=py35_0
- pyparsing=2.1.1=py35_0
- pyqt=4.11.4=py35_1
- pytables=3.2.2=np110py35_3
- python=3.5.1=0
- python-dateutil=2.5.2=py35_0
- pytz=2016.3=py35_0
- pyyaml=3.11=py35_1
- pyzmq=15.2.0=py35_0
- qt=4.8.7=1
- qtconsole=4.2.1=py35_0
- readline=6.2=2
- requests=2.9.1=py35_0
- setuptools=20.7.0=py35_0
- simplegeneric=0.8.1=py35_0
- sip=4.16.9=py35_0
- six=1.10.0=py35_0
- sqlite=3.9.2=0
- terminado=0.5=py35_1
- tk=8.5.18=0
- toolz=0.7.4=py35_0
- tornado=4.3=py35_0
- traitlets=4.2.1=py35_0
- wheel=0.29.0=py35_0
- xz=5.0.5=1
- yaml=0.1.6=0
- zlib=1.2.8=0
- pip:
  - backports.shutil-get-terminal-size==1.0.0
  - feather-format==0.2.0
  - ipython-genutils==0.1.0
  - jupyter-client==4.2.2
  - jupyter-console==4.1.1
  - jupyter-core==4.1.0
  - tables==3.2.2

